# This file contains configuration flags to customize your site
title: R Tutorials for Data Analytics
# Name of your site (displayed in the header)
# Short bio or description (displayed in the header)
description: Lessons and reviews to advance your R skills
# Theme
theme: jekyll-theme-minimal
# google_analytics
google_analytics: UA-59780775-1
